# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1d0zqb0rksacwfq22kzcv06j7pib7vaab4pkk4z75q417vky2338";
    aarch64-linux = "09bx0nh4nr247n0rxrr59l1n45l5bh8scbrxqz1rqjaj9siy15c3";
    x86_64-darwin = "10wk627gi71wdna88f85p900n0dvs9savawr2f0iqynfq8a2dmc4";
    aarch64-darwin = "07f4b3var87lwl179a84c8m7wc3n8kq9lxk7gcnrnv1avg7r4vxx";
  };

  urlMap = {
    x86_64-linux = "https://github.com/CircleCI-Public/chunk-cli/releases/download/v0.6.4/chunk-cli_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/CircleCI-Public/chunk-cli/releases/download/v0.6.4/chunk-cli_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/CircleCI-Public/chunk-cli/releases/download/v0.6.4/chunk-cli_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/CircleCI-Public/chunk-cli/releases/download/v0.6.4/chunk-cli_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "chunk";
  version = "0.6.4";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp chunk $out/bin/
  '';

  meta = {
    description = "Chunk CLI by CircleCI";
    homepage = "https://github.com/CircleCI-Public/chunk-cli";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
