# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "1vvl2php4ig34fbp54ndn2ddk0x9fx37fdrlcii5d2ggkmvn7i5g";
    aarch64-linux = "19m2jp2nqqrbry3hyb8n84q288mngs6yb00lxlfnqfkzgy4l60n3";
    x86_64-darwin = "1dagby4kr39dvb1y3ks2hzswg3ak3jwi9hc0njwcqkwfrnykp0kz";
    aarch64-darwin = "141rapjzj50d83p0vknnhilcijssfaybxbckd91vfx2n728zfn9w";
  };

  urlMap = {
    x86_64-linux = "https://github.com/CircleCI-Public/chunk-cli/releases/download//chunk-cli_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/CircleCI-Public/chunk-cli/releases/download//chunk-cli_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/CircleCI-Public/chunk-cli/releases/download//chunk-cli_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/CircleCI-Public/chunk-cli/releases/download//chunk-cli_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "chunk";
  version = "";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp chunk $out/bin/
  '';

  system = system;

  meta = {
    description = "Chunk CLI by CircleCI";
    homepage = "https://github.com/CircleCI-Public/chunk-cli";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
