# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "048lchva938x0z0797whzz4cj3xwdy4fwv0kn4cpnskrbrrc5f49";
    aarch64-linux = "16p6ar43axk089mmv8x1lf9qajm0dcr5d9nmqfr8sjxs70y5xb55";
    x86_64-darwin = "0549sz03qi53lhnbyp9zzcfkipxcj08y69hwhv9y3aflb9c6kn1q";
    aarch64-darwin = "16bvpgpbc6ss9w7g9ax9m46y6jgvqax10xsvrzdbx3lhal84sjky";
  };

  urlMap = {
    x86_64-linux = "https://github.com/CircleCI-Public/chunk-cli/releases/download/v0.6.5/chunk-cli_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/CircleCI-Public/chunk-cli/releases/download/v0.6.5/chunk-cli_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/CircleCI-Public/chunk-cli/releases/download/v0.6.5/chunk-cli_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/CircleCI-Public/chunk-cli/releases/download/v0.6.5/chunk-cli_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "chunk";
  version = "0.6.5";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp chunk $out/bin/
  '';

  meta = {
    description = "Chunk CLI by CircleCI";
    homepage = "https://github.com/CircleCI-Public/chunk-cli";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
